In [1]:
import numpy as np
from collections import defaultdict 

# number of clusters 
K = 3

class point():
    def __init__(self, data):
        self.data = data
        self.k = np.random.randint(0,K)
    
    def __repr__(self):
        return str({"data": self.data, "k": self.k})

In [2]:
# number of data points in total
N = 200
data1 = np.random.randn(N//3, 2) + np.array([5, 6])
data2 = np.random.randn(N//3, 2) + np.array([-5, -6])
data3 = np.random.randn(N//3, 2) + np.array([-10, 3])
data = np.concatenate((data1, data2, data3))

In [3]:
points = [point(d) for d in data]

In [4]:
def make_k_mapping(points):
    point_dict = defaultdict(list) # each element in the dict is a list
    for p in points:
        point_dict[p.k] = point_dict[p.k] + [p.data] # append new data points to the list
    return point_dict

In [5]:
def calc_k_means(point_dict):
    return [np.mean(point_dict[k], axis=0) for k in range(K)] # todo: plot the changes of these

In [6]:
def update_k(points, means):
    for p in points:
        distances = [np.linalg.norm(means[k]-p.data) for k in range(K)]  # calculate distances from each point to each mean
        p.k = np.argmin(distances) # assign point to the nearest cluster

In [7]:
def fit(points, epochs = 10):
    for e in range(epochs):
        point_dict = make_k_mapping(points)
        means = calc_k_means(point_dict)
        update_k(points, means)
    return means, points

In [8]:
new_means, new_points = fit(points)
new_means

[array([4.94130148, 5.81981546]),
 array([-10.14397415,   2.90692553]),
 array([-4.85511077, -6.01602397])]

In [9]:
from k_means import KMeans
clt = KMeans(3)
clt.fit(data)
clt.means

[array([-10.14397415,   2.90692553]),
 array([4.94130148, 5.81981546]),
 array([-4.85511077, -6.01602397])]